cookie:
  expiry_days: 30
  key: aqwsedrftyj12324354657gfds
  name: auth_cookie
credentials:
  usernames:
    abc:
      email: abc@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: abc
      password: $2b$12$BdDX6H1bTIn0vD5gbRYkm.QJYklDzYqhkgH8OI1u2cO8W3QZkudiu
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$q2CMB9mGtOlYjS0kxTzRkuDvGV.cL9sPu01mE2f1X9YCeAVduHp7i
    anu:
      email: anu@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: anu
      password: $2b$12$jFfzESjy1vlFo3GYofaRy.g6BS1Usi2Qpv/un7klzdgZDbkNBiDha
    anu1:
      email: anu1@gmail.com
      logged_in: false
      name: anu
      password: $2b$12$RWorzSJenQcMfEq1JI3bWuXqEKCnbSJ3hdxSBLPa5VtYZi377Rglu
    pqr:
      email: pqr@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: pqr
      password: $2b$12$LxIJhBYqq7MSdlHPCdkqjud6uuI1WFHwtE7QfT3z4Vlb2PXuNfzMS
    sample:
      email: sample@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: sample
      password: $2b$12$2XC0dKX3zaquUhNknZ.EuuDM.t2e0NymyDeu3qpTbsEcdTRetOuki
    test:
      email: test@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: test
      password: $2b$12$2RK1B8AN/T4UbnzGihdnPuXoLB2VfoSWZYa.gzRBMRFJU7HukWPvK
pre-authorized:
  emails:
  - admin@gmail.com
